### PR TITLE
fix: allow "id" instead of "objectID" again

### LINKED ISSUE #55: not finished onPostBuild
Hi,
I created a simple gatsby project and integrated the algolia appropriately.
But when I say **yarn build**.  I get the following error.

```
Algolia: 1 queries to index
Algolia: query 0: executing query
⠴ onPostBuild
not finished onPostBuild - 0.493s
```
i can't make sense. What exactly is the problem?

my gatsyby.config
```

require("dotenv").config({
  path: `.env.${process.env.NODE_ENV}`,
})

const blogQuery = `
  {
    allMarkdownRemark {
      nodes {
        frontmatter {
          title
          date
          description
        }
        fields {
          slug
        }
        html
      }
    }
  }
`

const queries = [
  {
    query: blogQuery,
    transformer: ({ data }) => {
      return data.allMarkdownRemark.nodes;
    },
  },
]


module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    {
      resolve: "gatsby-plugin-algolia",
      options: {
        appId: process.env.ALGOLIA_APP_ID,
        apiKey: process.env.ALGOLIA_API_KEY,
        indexName: process.env.ALGOLIA_INDEX_NAME,
        queries,
        chunkSize: 1000,
      },
    },
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/blog`,
        name: `blog`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/assets`,
        name: `assets`,
      },
    },
    `gatsby-transformer-remark`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
  ],
}

```

### PR DESCRIPTION
**Pull request by ahmetkuslular**
Since it accepted the `objectID` not coming before, it started to receive an error in cases where the `objectID` was not passed from `version 0.8`.

I think this should be true even if the `objectID` is not correct to be managed by algolia.

It should also accept the default id bypassing the `objectID`.

For this, if the `objectID` or `id` is missing, I let it add normally without comparison. I also copied it to use it as an `objectID` if id came.

fixes #55

### CODE REVIEW

File: gatsby-node.js [hunk 1]
```diff
@@ -124,23 +118,29 @@ exports.onPostBuild = async function (
         `query ${i}: found ${nbMatchedRecords} existing records`
       );
 
+      if(objects.length > 0 && !objects[0].objectID && objects[0].id){
```
Comment (Haroenv) [inline gatsby-node.js:121]: in theory we should do this check for every case, so I think it's actually already duplicating with the fix you did later, so this code isn't needed

File: gatsby-node.js [hunk 2]
```diff
@@ -124,23 +118,29 @@ exports.onPostBuild = async function (
...
+        objects.map(curObj => curObj.objectID = curObj.id)
+      }
+
       if (nbMatchedRecords) {
-        hasChanged = objects.filter((curObj) => {
-          const ID = curObj.objectID;
-          let extObj = algoliaObjects[ID];
+        if (objects.length > 0 && objects[0].objectID) {
```
Comment (Haroenv) [inline gatsby-node.js:126]: this line isn't needed

File: gatsby-node.js [hunk 3]
```diff
@@ -124,23 +118,29 @@ exports.onPostBuild = async function (
         `query ${i}: found ${nbMatchedRecords} existing records`
       );
 
+      if(objects.length > 0 && !objects[0].objectID && objects[0].id){
+        objects.map(curObj => curObj.objectID = curObj.id)
```
Comment (Haroenv) [inline gatsby-node.js:122]: this line can still be used, but not here

File: gatsby-node.js [hunk 4]
```diff
@@ -100,12 +100,6 @@ exports.onPostBuild = async function (
 
     const objects = await transformer(result);
```
Comment (Haroenv) [inline gatsby-node.js:101]:
```suggestion
    const objects = await transformer(result).map(object => ({ objectID: object.objectID || object.id, ...object }));
```

this is very similar to your fix

File: gatsby-node.js [hunk 5]
```diff
@@ -100,12 +100,6 @@ exports.onPostBuild = async function (
...
 
-    if (objects.length > 0 && !objects[0].objectID) {
```
Comment (Haroenv) [inline gatsby-node.js:103]: this error then would need to be put back (in case no object id or id)

Comment (ahmetkuslular) [reply gatsby-node.js:103]: why don't we accept this situation. There is no restriction on the algolia side. 🤔

Comment (Haroenv) [reply gatsby-node.js:103]: if you don't have an objectID, you won't be able to find those records again for updating later, and will be forced to fall back to a full reindex, which is more operations

Comment (ahmetkuslular) [reply gatsby-node.js:103]: https://www.algolia.com/doc/guides/sending-and-managing-data/send-and-update-your-data/#unique-identifier---objectid 

I know this situation, but as I said, there is no restriction. But it's not a problem if we make it mandatory 👍

**Comment by Haroenv** [comment]
Thanks @ahmetkuslular! I've published this in 0.8.1

**Comment by ahmetkuslular** [comment]
thank you for your time @Haroenv
